# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: ee1b831c7c728e61884a1670e2134afff795cfb103438cc970e35a386866ac3eee2f268f6fa007332da8cd4c1522799df60ff42e1160b568933b59cab4ca3134

test:
  domain_name: example.com 
  secret_key_base: a71edfa1be2aa1ffb1e4ffd70ccff8257432a01d5a46631f89ab6d52ff2afa7f18edc57c8ac2b462eaf09b9aaef707f6630be84c6ae4801a8f4a909339d2530b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
